spring:
  application:
    name: spotify-clone-be
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:spotify_clone_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
      hibernate:
          ddl-auto: create
      show-sql: true